### PR TITLE
Rewrite asdbctl to use HIDAPI instead of raw USB access

### PR DESCRIPTION
**Pull request by juliuszint**
In combination with the UDEV rule, this allows us to run this program
without root permissions and every authenticated user on the system can
get/set the brightness of the attached display.

Technically the Rust HID API create supports windows, so we might also be able
to make it work there.

### CODE REVIEW

**Comment by scivision** [comment]
In case it is helpful to you, here is an Apple Studio Display control from Windows using HID in C++

https://github.com/sfjohnson/studio-brightness

**Comment by flightmansam** [comment]
Has this been working well? Would love to build it into some Gnome extension slider

**Comment by flightmansam** [comment]
Have built this PR and can say it works like a charm: Gnome brightness extension available here: https://github.com/flightmansam/gnome-asdbctl-slider

**Comment by ecrsail** [comment]
I have been using the command-line utility for awhile now and found it
trivial to build and easy to use.

The only issue I encountered was that the value received when querying the
current brightness level is scaled differently than when setting
brightness.   I have not bothered to investigate whether this is by design
or not.

Hope to see the functionality included in a future Ubuntu kernel, but in
the interim many thanks to Sam for sharing his gnome extension!   I will be
investigating it shortly.

--Eric

**Comment by juliuszint** [comment]
> I have been using the command-line utility for awhile now and found it trivial to build and easy to use. The only issue I encountered was that the value received when querying the current brightness level is scaled differently than when setting brightness.

I would like to understand this a little bit better. I think this was the case before the HID rewrite. Would you mind testing this MR to check, if your issue is still there?

When I set the value to lets say 50% and then query it, it will return 50%.

**Comment by juliuszint** [comment]
I made a small improvement to the `udev` and if nothing more comes up, I will probably merge this soon.

**Comment by flightmansam** [comment]
It may be just because I'm using Asahi Linux and things are getting a bit weird with devices, but maybe every one in four or one in five times when I plug in the display, there's no /dev/ device coming up (and therefore throws the no display connected error) but that's hard to test. It could just be me. If I had more Linux machines near me, I would try it on another Linux device just to check that it's just not just me.

**Comment by juliuszint** [comment]
> It may be just because I'm using Asahi Linux and things are getting a bit weird with devices, but maybe every one in four or one in five times when I plug in the display, there's no /dev/ device coming up (and therefore throws the no display connected error) but that's hard to test. It could just be me. If I had more Linux machines near me, I would try it on another Linux device just to check that it's just not just me.

I also have seen this issue and have just fixed the udev rule. Can you update it on your machine as well and see, if it still reproduces? I have also added a fallback in cases where the UDEV rule is not present, but I think this still requires root then. Not sure what the default permissions are for hid devices.

**Comment by flightmansam** [comment]
Will check it out!

**Comment by flightmansam** [comment]
I've now tested your latest commits and I've tested it on a completely different computer now, an x86 AMD (fedora 41) system. It seems like, at least from my testing, if you disconnect the display and reconnect it, it won't show up in /dev. And then if you disconnect and reconnect it one more time, it will show up. So every second time it doesn't show up in /dev? Although it seems from boot, it will always show up first time (I think).

**Comment by juliuszint** [comment]
> I've now tested your latest commits and I've tested it on a completely different computer now, an x86 AMD (fedora 41) system. It seems like, at least from my testing, if you disconnect the display and reconnect it, it won't show up in /dev. And then if you disconnect and reconnect it one more time, it will show up. So every second time it doesn't show up in /dev? Although it seems from boot, it will always show up first time (I think).

Now this is strange. I have tested here once more, with and without the udev rule, plugging in and unplugging, but it works every time. Could you share the output of the following commands?

```
/bin/ls -l /sys/class/hidraw | grep :1.7

cat /etc/udev/rules.d/20-asd-backlight.rules
```

**Comment by flightmansam** [comment]
```sh
(base) samuel@fedora:~$ cat /etc/udev/rules.d/20-asd-backlight.rules
SUBSYSTEM=="hidraw", DEVPATH=="*:1.7/[0-9][0-9][0-9][0-9]:05AC:1114.[0-9][0-9][0-9][0-9]/*", ATTRS{idVendor}=="05ac", ATTRS{idProduct}=="1114", MODE="0660", TAG+="uaccess", SYMLINK+="asdbl-%s{serial}"
```

without display plugged in (no grep):
```sh
(base) samuel@fedora:~$ /bin/ls -l /sys/class/hidraw 
total 0
lrwxrwxrwx. 1 root root 0 Dec 10 20:58 hidraw0 -> ../../devices/platform/soc/39b10c000.spi/spi_master/spi1/spi1.0/001C:05AC:0343.0002/hidraw/hidraw0
lrwxrwxrwx. 1 root root 0 Dec 10 20:58 hidraw1 -> ../../devices/platform/soc/39b10c000.spi/spi_master/spi1/spi1.0/001C:05AC:0343.0001/hidraw/hidraw1
```

with display plugged in:
```sh
(base) samuel@fedora:~$ /bin/ls -l /sys/class/hidraw | grep :1.7
lrwxrwxrwx. 1 root root 0 Dec 11 14:11 hidraw7 -> ../../devices/platform/soc/f02280000.usb/xhci-hcd.0.auto/usb1/1-1/1-1.4/1-1.4:1.7/0003:05AC:1114.0020/hidraw/hidraw7

```

**Comment by juliuszint** [comment]
> ```shell
> (base) samuel@fedora:~$ cat /etc/udev/rules.d/20-asd-backlight.rules
> SUBSYSTEM=="hidraw", DEVPATH=="*:1.7/[0-9][0-9][0-9][0-9]:05AC:1114.[0-9][0-9][0-9][0-9]/*", ATTRS{idVendor}=="05ac", ATTRS{idProduct}=="1114", MODE="0660", TAG+="uaccess", SYMLINK+="asdbl-%s{serial}"
> ```

Ah, this here is the problem. Its still the old udev rule, the new one has `[0-9]` switched to `?`. You can take the fixed one from here: https://github.com/juliuszint/asdbctl/blob/826e221bc8c2853f2dd2f33e43b1443d1ade5dce/rules.d/20-asd-backlight.rules

**Comment by flightmansam** [comment]
Ah, I thought it might be something like that. You legend. I'll check it out when I get home. Thanks.

**Comment by flightmansam** [comment]
Working like a charm now!

**Comment by juliuszint** [comment]
Awesome! Thanks everyone in here for testing things and pointing out problems. Will merge it now.

**Comment by flightmansam** [comment]
Wooo! Excellent work thank you so much Juliuszint!

**Pull request merged**
